### ISSUE TITLE
Using MongoDB instead of MariaDB or MySQL 

### ISSUE THREAD

**Issue by ValoTreff** [NoobCloudSystems/NoobCloud#3]
Its better to use MongoDB cause the Service is build as json and for using in near future maybe Modules(Social System) its easier to add them.

**Comment by Luccboy** [comment]
Thank you for this idea. I will definetely add MongoDB support!

**Comment by Luccboy** [comment]
Added in https://github.com/NoobCloudSystems/NoobCloud/commit/c4a07aaa808fbd77e1e30560701e705b155e8056
