### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by ValoTreff** [NoobCloudSystems/NoobCloud#4]
Pls write me at Twitter. @Rioth4ppii

**Comment by Luccboy** [comment]
Hey, is there a reason why do you want to write on Twitter? Please keep things, that might interest and concern others, here on GitHub.

**Comment by Luccboy** [comment]
@ValoTreff ?

**Comment by ValoTreff** [comment]
Ich sehe grade du bist deutsch ^^
Ich wollte aus privaten gründen mal mit dir reden wenn es geht, schreibe ejdoch nicht mein Dc und so hier rein c:

**Comment by Luccboy** [comment]
Ich folge dir jetzt, du müsstest mir auch folgen, damit ich dir schreiben kann, oder du schreibst mir :)
